package com.glooshy.ships.combat;

import org.bukkit.Material;

/**
 * Furnace-style fuel values for cannon shot generation (Session 2). One fuel
 * item is consumed at fire time (never while idle) and converts its burn
 * ticks into charged shots.
 */
public final class CannonFuels {

    /** Burn ticks per generated shot (coal = 1600 → 4 shots). */
    public static final int TICKS_PER_SHOT = 400;

    /** Furnace burn ticks for a material; 0 = not a fuel. */
    public static int burnTicks(Material material) {
        return switch (material) {
            case COAL, CHARCOAL -> 1600;
            case BLAZE_ROD -> 2400;
            case COAL_BLOCK -> 16000;
            case DRIED_KELP_BLOCK -> 4000;
            case LAVA_BUCKET -> 20000;
            case WOODEN_SHOVEL, WOODEN_PICKAXE, WOODEN_AXE, WOODEN_HOE, WOODEN_SWORD -> 200;
            case BOOKSHELF, CHEST, TRAPPED_CHEST, CRAFTING_TABLE, FLETCHING_TABLE,
                 LOOM, BARREL, SMOKER, BLAST_FURNACE, CARTOGRAPHY_TABLE,
                 COMPOSTER, NOTE_BLOCK, JUKEBOX -> 300;
            case STICK, BOWL, LADDER -> 100;
            default -> material.name().endsWith("_PLANKS") || material.name().endsWith("_LOG")
                    || material.name().endsWith("_WOOD") || material.name().endsWith("_FENCE")
                    ? 300 : 0;
        };
    }

    public static boolean isFuel(Material material) {
        return burnTicks(material) > 0;
    }

    /** Shots generated by one fuel item (always at least one). */
    public static int shotsFor(Material material) {
        return Math.max(1, burnTicks(material) / TICKS_PER_SHOT);
    }

    private CannonFuels() {
    }
}
